"""initial migration

Revision ID: 240386a60e21
Revises: 
Create Date: 2024-02-03 12:46:06.415448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240386a60e21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input1', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('input2', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('input3', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('input4', sa.String(length=255), nullable=False))
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('input4')
        batch_op.drop_column('input3')
        batch_op.drop_column('input2')
        batch_op.drop_column('input1')

    # ### end Alembic commands ###
